export enum EnvName {
    CONFIG_PATH = 'WS_SCRCPY_CONFIG',
    WS_SCRCPY_PATHNAME = 'WS_SCRCPY_PATHNAME',
    PORT = 'PORT',
    RBOX_SERVICE_PORT = 'RBOX_SERVICE_PORT',
    INTERNAL_API_SECRET = 'INTERNAL_API_SECRET',
}
